# Base image
FROM node:22-slim AS base
WORKDIR /app
RUN corepack enable

# Dependencies
FROM base AS deps
COPY package*.json ./
COPY database/package*.json ./database/
RUN npm install

# Builder
FROM base AS builder
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npx prisma generate --schema=database/prisma/schema.prisma
RUN npm run build

# Runner
FROM base AS runner
ENV NODE_ENV=production
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nestjs

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/database ./database
COPY --from=builder /app/package.json ./package.json

USER nestjs
EXPOSE 4000
CMD ["npm", "run", "start:prod"]
